version: "3"
services:
 mysql:
  image: mysql:8.0
  container_name: polychat-mysql
  ports:
   - "3306:3306"
  env_file: .env
  environment:
   MYSQL_DATABASE: ${MYSQL_DATABASE}
  volumes:
   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
