name: Node.js CI

on:
 push:
  branches:
   - main
 pull_request:
  branches:
   - main

jobs:
 build:
  name: Build and Test
  runs-on: ubuntu-latest

  strategy:
   matrix:
    node-version: [21]

  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Setup Node.js
     uses: actions/setup-node@v4
     with:
      node-version: ${{ matrix.node-version }}

   - name: Change directory to backend
     run: cd backend

   - name: Install dependencies
     run: npm install
     working-directory: ./backend

   - name: Run tests
     run: npm test
     working-directory: ./backend
